service: serverless-webpack-example
plugins:
  - serverless-webpack
  - serverless-offline
provider:
  memorySize: 128
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  stage: dev
  versionFunctions: false
functions:
  findManyPet:
    events:
      - http:
          method: GET
          path: pets
    handler: ./src/api/handlers/PetFindManyHandler.handler

  findOneByIdPet:
    events:
      - http:
          method: GET
          path: pets/{id}
    handler: ./src/api/handlers/PetFindOneByIdHandler.handler

  findManyTutor:
    events:
      - http:
          method: GET
          path: tutors
    handler: ./src/api/handlers/TutorFindManyHandler.handler

  findOneByIdTutor:
    events:
      - http:
          method: GET
          path: tutors/{id}
    handler: ./src/api/handlers/TutorFindOneByIdHandler.handler

  insertTutor:
    events:
      - http:
          method: POST
          path: tutors
    handler: ./src/api/handlers/TutorInsertHandler.handler

  updateTutor:
    events:
      - http:
          method: PUT
          path: tutors/{id}
    handler: ./src/api/handlers/TutorUpdateHandler.handler

  deleteTutor:
    events:
      - http:
          method: DELETE
          path: tutors/{id}
    handler: ./src/api/handlers/TutorDeleteHandler.handler
    
  deletePet:
    events:
      - http:
          method: DELETE
          path: pets/{id}
    handler: ./src/api/handlers/PetDeleteHandler.handler
  
  updatePet:
    events:
      - http:
          method: PUT
          path: pets/{id}
    handler: ./src/api/handlers/PetUpdateHandler.handler
  
  insertPet:
    events:
      - http:
          method: POST
          path: pets
    handler: ./src/api/handlers/PetInsertHandler.handler