service: serverless-webpack-example
plugins:
  - serverless-webpack
  - serverless-offline
provider:
  memorySize: 128
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  stage: dev
  versionFunctions: false
functions:
  findManyPet:
    events:
      - http:
          method: GET
          path: pets
    handler: ./src/api/handlers/PetFindManyHandler.handler
    # cors: true # Setting cors to true assumes a default configuration 

  findOneByIdPet:
    events:
      - http:
          method: GET
          path: pets/{id}
    handler: ./src/api/handlers/PetFindOneByIdHandler.handler

  deletePet:
    events:
      - http:
          method: DELETE
          path: pets/{id}
    handler: ./src/api/handlers/PetDeleteHandler.handler
  
  updatePet:
    events:
      - http:
          method: PUT
          path: pets/{id}
    handler: ./src/api/handlers/PetUpdateHandler.handler
  
  insertPet:
    events:
      - http:
          method: POST
          path: pets
    handler: ./src/api/handlers/PetInsertHandler.handler